version: '3.8'
services:
  mongodb-rag-it: #修改服务名，避免冲突
    image: mongo:latest
    container_name: mongodb-rag-it # 修改为it知识库的新容器名
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 121314
    volumes:
      - ../mongodb_data_it:/data/db # 修改为it知识库的新数据存储路径
    ports:
      - "27018:27017" # 修改为it知识库的新端口27018
