version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.22.3
    restart: always
    ports:
      - "1238:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'  # 关闭默认的自动向量化
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'weaviate-node1'
    volumes:
      - ./weaviate_data:/var/lib/weaviate
