max_loop: 1

models:
  default:
    endpoint: "http://10.180.116.5:6391/v1"
    key: "SOME_KEY"
    temperature: 0.7
    model_name: "qwen3"
    thinking: false
  qwen3-reasoning:
    endpoint: "http://10.180.116.5:6391/v1"
    key: "SOME_KEY"
    temperature: 0.7
    model_name: "qwen3-reasoning"
    thinking: true


modules:
  question_classification:
    default_model: "default"
  commercial_api:
    default_model: "default"
  question_optimization:
    enable: true
    default_model: "default"
  answer_generation:
    default_model: "default"
  answer_evaluation:
    default_model: "default"
  summarization:
    default_model: "default"
  translation:
    default_model: "default"
  doc_metadata:
    default_model: "default"
  document_abstract:
    default_model: "default"
  page_abstract:
    default_model: "default"
  refine_page_text:
    default_model: "default"
  universal_chat:
    default_model: "default"
  personal_knowledge_base:
    default_model: "default"
  prompt_filler:
    default_model: "default"

context_retrieval:
  weaviate_endpoint: "http://10.180.116.2:8085" # 修改为it知识库的weaviate服务的新端口8085
  embedding_endpoint: "http://10.180.116.2:8000/embed/" # 单个向量生成接口
  embedding_batch_endpoint: "http://10.180.116.5:8000/embed_batch/"

mongodb:
  mongodb_connection_string: "10.180.116.2:27018" # 修改为it知识库的mongodb服务的新端口27018

tokenizer_service:
  tokenizer_endpoint: "http://10.180.116.2:15000" # token计数接口

minio:
  minio_endpoint: "10.180.248.141:9000"
  minio_access_key: "minioadmin"
  minio_secret_key: "G3j+-G]aMX%bc/Wt"
  minio_bucket: "ai-file"